name: mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_svg: ^1.1.6
  material_design_icons_flutter: ^5.0.6996
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.1
  google_sign_in: ^5.4.2
  get_storage: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/app/

  # fonts:
  #   - family: Font-tal
  #     fonts:
  #       - asset: fonts/Font-tal-Regular.ttf
  #       - asset: fonts/Font-tal-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
